namespace Flunt.Br.Document.Enum
{
    public enum StateEnum
    {
        Acre,
        Alagoas,
        Amazonas,
        Bahia,
        Amapa,
        Ceara,
        DistritoFederal,
        EspiritoSanto,
        Goias,
        Maranhao,
        MatoGrosso,
        MatoGrossoDoSul,
        MinasGerais,
        Para,
        Paraiba,
        Pernambuco,
        Piaui,
        Parana,
        RioDeJaneiro,
        RioGrandeDoNorte,
        Rondonia,
        Roraima,
        RioGrandeDoSul,
        SantaCatarina,
        Sergipe,
        SaoPaulo,
        Tocantins,
    }
}